# Generated by Django 5.0.1 on 2024-01-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(choices=[('ERP SOLUTIONS', 'Erp Solutions'), ('WEBSITE DEVELOPMENT', 'Website Development'), ('ECOMMERCE', 'E-Commerce'), ('MOBILE APP', 'Mobile App Development'), ('DIGITAL MARKETING', 'Digital Marketing')], max_length=150)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
